package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.46

import (
	"context"
	"encoding/json"
	"errors"
	"strconv"

	authv1 "watchtower/proto/gen/auth/v1"
	incidentv1 "watchtower/proto/gen/incident/v1"

	"watchtower/api/graph/generated"
	"watchtower/api/graph/model"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, name string, password string) (*model.AuthPayload, error) {
	if r.AuthClient == nil {
		return nil, errors.New("auth service unavailable")
	}
	resp, err := r.AuthClient.Register(ctx, &authv1.RegisterRequest{Email: email, Name: name, Password: password})
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{Token: resp.GetJwtToken(), User: &model.User{ID: resp.GetUser().GetId(), Email: resp.GetUser().GetEmail(), Name: resp.GetUser().GetName()}}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	if r.AuthClient == nil {
		return nil, errors.New("auth service unavailable")
	}
	resp, err := r.AuthClient.Login(ctx, &authv1.LoginRequest{Email: email, Password: password})
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{Token: resp.GetJwtToken(), User: &model.User{ID: resp.GetUser().GetId(), Email: resp.GetUser().GetEmail(), Name: resp.GetUser().GetName()}}, nil
}

// Incidents is the resolver for the incidents field.
func (r *queryResolver) Incidents(ctx context.Context) ([]model.Incident, error) {
	if uid := ctx.Value("userID"); uid == nil {
		return nil, errors.New("unauthorized")
	}
	if r.IncidentClient == nil {
		return nil, errors.New("incident service unavailable")
	}
	resp, err := r.IncidentClient.ListIncidents(ctx, &incidentv1.ListIncidentsRequest{Limit: 50})
	if err != nil {
		return nil, err
	}
	out := make([]model.Incident, 0, len(resp.GetIncidents()))
	for _, it := range resp.GetIncidents() {
		out = append(out, model.Incident{ID: it.GetId(), Title: it.GetTitle()})
	}
	return out, nil
}

// OnNewIncident is the resolver for the onNewIncident field.
func (r *subscriptionResolver) OnNewIncident(ctx context.Context) (<-chan *model.Incident, error) {
	ch := make(chan *model.Incident, 1)
	pubsub := r.Redis.Subscribe(ctx, "incidents:new")
	// ensure subscription started
	if _, err := pubsub.Receive(ctx); err != nil {
		return nil, err
	}
	go func() {
		defer close(ch)
		defer pubsub.Close()
		for {
			select {
			case <-ctx.Done():
				return
			case msg, ok := <-pubsub.Channel():
				if !ok {
					return
				}
				var m struct {
					ID    int64  `json:"id"`
					Title string `json:"title"`
				}
				if err := json.Unmarshal([]byte(msg.Payload), &m); err == nil {
					ch <- &model.Incident{ID: strconv.FormatInt(m.ID, 10), Title: m.Title}
				}
			}
		}
	}()
	return ch, nil
}

// JWT signing moved to auth-service.

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
