// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Comment struct {
	ID        string `json:"id"`
	Text      string `json:"text"`
	Author    *User  `json:"author,omitempty"`
	CreatedAt string `json:"createdAt"`
}

type Incident struct {
	ID       string    `json:"id"`
	Title    string    `json:"title"`
	Severity string    `json:"severity"`
	Status   string    `json:"status"`
	Details  *string   `json:"details,omitempty"`
	Assignee *User     `json:"assignee,omitempty"`
	Comments []Comment `json:"comments,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
	Name  string `json:"name"`
}
